compile:
	mpic++ -std=c++17 main.cpp -o a2
run:
	# mpirun -np 32 ./a2 --taskid=1 --inputpath=test_cases/test1/test-input-1.gra --headerpath=test_cases/test1/test-header-1.dat --outputpath=test_cases/test1/out0.txt --verbose=0 --startk=1 --endk=10
	# mpirun -np 32 ./a2 --taskid=1 --inputpath=test_cases/test1/test-input-1.gra --headerpath=test_cases/test1/test-header-1.dat --outputpath=test_cases/test1/out1.txt --verbose=1 --startk=1 --endk=10
clean:
	rm a2
